# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pool_poolmembership_usercontribution_userpointmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Goal Name')),
                ('description', models.CharField(max_length=200, verbose_name='Goal description')),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='balance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpointmovement',
            name='balance',
            field=models.IntegerField(blank=True),
        ),
    ]
