# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161021_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Lottery Name')),
                ('description', models.CharField(max_length=200, verbose_name='Lottery description')),
                ('total_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLotteryTicketMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_amount', models.IntegerField()),
                ('balance', models.IntegerField(blank=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='poolmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='poolmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercontribution',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userpointmovement',
            name='group',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='PoolMembership',
        ),
    ]
